### ISSUE TITLE
Some Moves Seem to be left out?

### ISSUE THREAD

**Issue by Gypsum05** [matt1484/pokemon-unite-designer#1]
I've noticed that depending on the Pokemon in Question, a few moves tend to get left out of the available move list. The two groups I've noticed being left out are **Moves exclusive to prior Evolutions**, such as Breloom's spore, and **Egg moves that have maintained their status as such for the Pokemon's entire History** such as Crawdaunt's Aqua jet. 

I Have no clue if this is a known issue, but i figure I should bring it up.

**Comment by matt1484** [comment]
Probably an issue with how the data is stored. I can probably fix that pretty easy. Thanks
